# Generated by Django 5.1.7 on 2025-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="id",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("nick_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("nexon_api_key", models.CharField(max_length=200)),
            ],
        ),
    ]
