# Generated by Django 5.2.8 on 2025-11-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nexon_api_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='id',
        ),
    ]
