# Generated by Django 5.1.7 on 2025-12-25 05:52

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="문서 ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="문서 제목")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="출처 URL 또는 파일명",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("guide", "가이드"),
                            ("notice", "공지사항"),
                            ("item", "아이템 정보"),
                            ("quest", "퀘스트 정보"),
                            ("skill", "스킬 정보"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="문서 타입",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="추가 메타데이터"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
            ],
            options={
                "verbose_name": "RAG 문서",
                "verbose_name_plural": "RAG 문서",
                "db_table": "mai_rag_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type"], name="mai_rag_doc_content_56647c_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="mai_rag_doc_created_38cee5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="청크 ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="청크 내용")),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="원본 문서 내에서의 순서", verbose_name="청크 순서"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="청크 메타데이터"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        null=True,
                        verbose_name="청크 임베딩",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="rag.document",
                        verbose_name="원본 문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "문서 청크",
                "verbose_name_plural": "문서 청크",
                "db_table": "mai_rag_chunk",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="mai_rag_chu_documen_8f1431_idx",
                    )
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
