# Generated by Django 5.1.7 on 2025-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nexon_api_key",
            field=models.CharField(
                blank=True,
                help_text="넥슨 오픈 API 키 (선택사항)",
                max_length=255,
                null=True,
                verbose_name="넥슨 API 키",
            ),
        ),
    ]
