# Generated by Django 5.1.7 on 2025-12-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_nexon_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="maple_nickname",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nexon_api_key",
            field=models.CharField(
                blank=True,
                help_text="넥슨 오픈 API 키",
                max_length=255,
                null=True,
                verbose_name="넥슨 API 키",
            ),
        ),
    ]
