# Generated by Django 5.1.7 on 2025-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_maple_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="maple_nickname",
            field=models.CharField(
                blank=True,
                help_text="메이플 닉네임",
                max_length=255,
                null=True,
                verbose_name="메이플 닉네임",
            ),
        ),
    ]
