# Generated by Django 5.1.7 on 2025-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_maple_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="character_ocid",
            field=models.CharField(
                blank=True,
                help_text="캐릭터 OCID",
                max_length=255,
                null=True,
                verbose_name="캐릭터 OCID",
            ),
        ),
    ]
