# Generated by Django 5.1.7 on 2025-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mai_chat", "0002_alter_chatsession_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LangGraphCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=255, verbose_name="스레드 ID (세션 ID)"
                    ),
                ),
                (
                    "checkpoint_id",
                    models.CharField(max_length=255, verbose_name="체크포인트 ID"),
                ),
                (
                    "parent_checkpoint_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="부모 체크포인트 ID",
                    ),
                ),
                (
                    "checkpoint_data",
                    models.BinaryField(verbose_name="체크포인트 데이터"),
                ),
                ("metadata", models.BinaryField(verbose_name="메타데이터")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "LangGraph 체크포인트",
                "verbose_name_plural": "LangGraph 체크포인트",
                "db_table": "mai_chat_checkpoint",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["thread_id", "-created_at"],
                        name="mai_chat_ch_thread__20ad41_idx",
                    )
                ],
            },
        ),
    ]
