openapi: 3.0.3
info:
  title: MAI Chatbot - Authentication API
  description: 메이플스토리 챗봇 프로젝트 - 인증/로그인 관련 API
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Django Development Server

paths:
  /auth/login/:
    post:
      tags:
        - Authentication
      summary: SNS 로그인
      description: Google, Kakao 등 SNS 계정을 통한 로그인 처리
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - provider
                - token
              properties:
                provider:
                  type: string
                  enum: [google, kakao, naver]
                  description: SNS 로그인 제공자
                  example: google
                token:
                  type: string
                  description: SNS에서 받은 액세스 토큰
                  example: "ya29.a0AfH6SMC..."
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          user_id:
                            type: integer
                            example: 1
                          nickname:
                            type: string
                            example: "창삣삐"
                          access_token:
                            type: string
                            description: JWT 액세스 토큰
                          refresh_token:
                            type: string
                            description: JWT 리프레시 토큰
        "400":
          description: 잘못된 토큰 또는 요청
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'
        "401":
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'

  /auth/logout/:
    post:
      tags:
        - Authentication
      summary: 로그아웃
      description: 현재 세션 종료 및 토큰 무효화
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 성공적으로 로그아웃
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
        "401":
          description: 인증되지 않은 요청
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'

  /auth/refresh/:
    post:
      tags:
        - Authentication
      summary: 토큰 갱신
      description: 리프레시 토큰을 사용하여 새로운 액세스 토큰 발급
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
                  description: 리프레시 토큰
      responses:
        "200":
          description: 토큰 갱신 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          access_token:
                            type: string
                          refresh_token:
                            type: string
        "401":
          description: 유효하지 않은 리프레시 토큰
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      $ref: '../schemas/common.yaml#/components/securitySchemes/bearerAuth'
