openapi: 3.0.3
info:
  title: MAI Chatbot - Chatbot API
  description: 메이플스토리 챗봇 프로젝트 - 챗봇 대화 관련 API
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Django Development Server

paths:
  /chatbot/ask/:
    post:
      tags:
        - Chatbot
      summary: 챗봇에게 질문하기
      description: 메이플스토리 관련 질문을 하고 AI 답변을 받습니다
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: 메이플스토리 관련 질문
                  example: "메이플에서 빠르게 레벨 올리는 법 알려줘"
                  minLength: 1
                  maxLength: 1000
                user_id:
                  type: string
                  description: 사용자 ID (선택사항, 대화 기록 저장용)
                  example: "user123"
      responses:
        "200":
          description: 챗봇 응답 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          answer:
                            type: string
                            description: AI가 생성한 답변
                            example: "빠른 레벨업을 위해서는 아케인 리버 지역에서..."
                          sources:
                            type: array
                            description: 답변 생성에 사용된 참고 문서들
                            items:
                              type: object
                              properties:
                                title:
                                  type: string
                                  example: "메이플스토리 레벨업 가이드"
                                snippet:
                                  type: string
                                  example: "아케인 리버에서는 일일 퀘스트를..."
                                score:
                                  type: number
                                  format: float
                                  description: 유사도 점수
                                  example: 0.85
                          conversation_id:
                            type: string
                            description: 대화 세션 ID
                            example: "conv_123456"
        "400":
          description: 잘못된 요청 (빈 질문 등)
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'
        "500":
          description: AI 모델 오류 또는 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'

  /chatbot/history/:
    get:
      tags:
        - Chatbot
      summary: 대화 기록 조회
      description: 특정 사용자의 챗봇 대화 기록을 조회합니다
      parameters:
        - $ref: '../schemas/common.yaml#/components/parameters/UserIdParam'
        - $ref: '../schemas/common.yaml#/components/parameters/LimitParam'
        - $ref: '../schemas/common.yaml#/components/parameters/PageParam'
        - name: conversation_id
          in: query
          description: 특정 대화 세션 ID로 필터링
          required: false
          schema:
            type: string
      responses:
        "200":
          description: 대화 기록 조회 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          conversations:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1
                                question:
                                  type: string
                                  example: "메이플에서 빠르게 레벨 올리는 법은?"
                                answer:
                                  type: string
                                  example: "아케인 리버 지역에서..."
                                conversation_id:
                                  type: string
                                  example: "conv_123456"
                                created_at:
                                  type: string
                                  format: date-time
                                  example: "2024-01-15T10:30:00Z"
                          pagination:
                            $ref: '../schemas/common.yaml#/components/schemas/PaginationMeta'
        "400":
          description: 잘못된 요청 파라미터
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'

  /chatbot/clear-history/:
    post:
      tags:
        - Chatbot
      summary: 대화 기록 초기화
      description: 특정 사용자의 챗봇 대화 기록을 삭제합니다
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  description: 기록을 삭제할 사용자 ID
                  example: "user123"
                conversation_id:
                  type: string
                  description: 특정 대화만 삭제 (선택사항)
                  example: "conv_123456"
      responses:
        "200":
          description: 대화 기록 삭제 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          deleted_count:
                            type: integer
                            description: 삭제된 대화 수
                            example: 15
        "400":
          description: 잘못된 요청 파라미터
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'

  /chatbot/health/:
    get:
      tags:
        - System
      summary: 챗봇 서비스 상태 확인
      description: 챗봇 AI 모델과 RAG 시스템의 상태를 확인합니다
      responses:
        "200":
          description: 서비스 정상 동작
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../schemas/common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          status:
                            type: string
                            enum: [healthy, degraded, down]
                            example: "healthy"
                          model_status:
                            type: string
                            description: AI 모델 상태
                            example: "loaded"
                          rag_status:
                            type: string
                            description: RAG 인덱스 상태
                            example: "indexed"
                          last_check:
                            type: string
                            format: date-time
                            example: "2024-01-15T10:30:00Z"
        "503":
          description: 서비스 사용 불가
          content:
            application/json:
              schema:
                $ref: '../schemas/common.yaml#/components/schemas/ErrorResponse'
