openapi: 3.0.3
info:
  title: MAI Chatbot - FastAPI Service
  description: 메이플스토리 챗봇 프로젝트 - FastAPI 기반 AI 모델 서비스
  version: 1.0.0

servers:
  - url: http://localhost:8001
    description: FastAPI AI Model Server

paths:
  /:
    get:
      tags:
        - System
      summary: FastAPI 서비스 루트
      description: FastAPI 서비스의 기본 정보를 반환합니다
      responses:
        "200":
          description: 서비스 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "MapleStory AI Chatbot API"
                  version:
                    type: string
                    example: "1.0.0"
                  docs_url:
                    type: string
                    example: "http://localhost:8001/docs"

  /health:
    get:
      tags:
        - System
      summary: FastAPI 서비스 헬스체크
      description: AI 모델 서비스의 상태를 확인합니다
      responses:
        "200":
          description: 서비스 정상
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  model_loaded:
                    type: boolean
                    example: true
                  gpu_available:
                    type: boolean
                    example: false
                  memory_usage:
                    type: object
                    properties:
                      used:
                        type: string
                        example: "2.1 GB"
                      available:
                        type: string
                        example: "5.9 GB"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-15T10:30:00Z"

  /api/chat:
    post:
      tags:
        - AI Model
      summary: AI 모델 직접 호출
      description: Django를 거치지 않고 직접 AI 모델에 질문을 전송합니다
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: 메이플스토리 관련 질문
                  example: "메이플스토리에서 가장 강한 직업은?"
                  minLength: 1
                  maxLength: 1000
                user_id:
                  type: string
                  description: 사용자 식별자 (선택사항)
                  example: "fastapi_user_123"
                temperature:
                  type: number
                  format: float
                  description: 모델 응답의 창의성 조절 (0.0-1.0)
                  minimum: 0.0
                  maximum: 1.0
                  default: 0.7
                  example: 0.7
                max_tokens:
                  type: integer
                  description: 최대 응답 토큰 수
                  minimum: 50
                  maximum: 2000
                  default: 500
                  example: 500
                stream:
                  type: boolean
                  description: 스트리밍 응답 여부
                  default: false
                  example: false
      responses:
        "200":
          description: AI 응답 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: AI 모델의 답변
                    example: "메이플스토리에서 가장 강한 직업은 현재 메타에 따라 다르지만..."
                  user_id:
                    type: string
                    description: 요청한 사용자 ID
                    example: "fastapi_user_123"
                  model_info:
                    type: object
                    properties:
                      model_name:
                        type: string
                        example: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
                      is_local:
                        type: boolean
                        description: 로컬 파인튜닝 모델 사용 여부
                        example: true
                      response_time:
                        type: number
                        format: float
                        description: 응답 생성 시간(초)
                        example: 2.35
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-15T10:30:00Z"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "질문이 너무 짧습니다"
                  error_code:
                    type: string
                    example: "INVALID_INPUT"
        "500":
          description: AI 모델 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "AI 모델 처리 중 오류가 발생했습니다"
                  error_code:
                    type: string
                    example: "MODEL_ERROR"

  /api/model/status:
    get:
      tags:
        - AI Model
      summary: AI 모델 상태 조회
      description: 현재 로드된 AI 모델의 상세 상태 정보를 조회합니다
      responses:
        "200":
          description: 모델 상태 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  model_loaded:
                    type: boolean
                    example: true
                  model_name:
                    type: string
                    example: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
                  model_path:
                    type: string
                    example: "/app/fine_tuned_model/merged_qwen"
                  is_local_model:
                    type: boolean
                    description: 로컬 파인튜닝 모델 사용 여부
                    example: true
                  model_parameters:
                    type: object
                    properties:
                      total_params:
                        type: string
                        example: "8.0B"
                      quantization:
                        type: string
                        example: "none"
                      device:
                        type: string
                        example: "cpu"
                  load_time:
                    type: number
                    format: float
                    description: 모델 로딩에 걸린 시간(초)
                    example: 45.2
                  last_used:
                    type: string
                    format: date-time
                    description: 마지막 사용 시간
                    example: "2024-01-15T10:25:00Z"

  /api/model/reload:
    post:
      tags:
        - AI Model
      summary: AI 모델 재로드
      description: 현재 로드된 AI 모델을 재로드합니다 (관리자 전용)
      security:
        - apiKeyAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                force:
                  type: boolean
                  description: 강제 재로드 여부
                  default: false
                  example: true
                model_path:
                  type: string
                  description: 특정 모델 경로로 재로드
                  example: "/app/models/custom_model"
      responses:
        "200":
          description: 모델 재로드 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "모델이 성공적으로 재로드되었습니다"
                  model_name:
                    type: string
                    example: "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
                  reload_time:
                    type: number
                    format: float
                    description: 재로드에 걸린 시간(초)
                    example: 42.1
        "403":
          description: 권한 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "관리자 권한이 필요합니다"
        "500":
          description: 재로드 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "모델 로딩 중 오류가 발생했습니다"

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: FastAPI 서비스 관리용 API 키
